import {keys,koreaNow,addDays,weekStart,dateLabel,validate,upcoming,parseTSV,mergeDays,validDate} from './core.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let published,displayData,week=weekStart(koreaNow().date),editStart=week,dirty=false,apiURL='',revision=null;
function status(text){$('#status').textContent=text;}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function localGet(key){try{return localStorage.getItem(key);}catch{return null;}}
function tab(id){if(!['next','weekly','admin'].includes(id))id='next';for(const s of ['next','weekly','admin'])$('#'+s).hidden=s!==id;$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===id);if(b.dataset.tab===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
$$('[data-tab]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.tab;tab(b.dataset.tab);});window.addEventListener('hashchange',()=>tab(location.hash.slice(1)));tab(location.hash.slice(1));
if(localGet('rnk-theme')==='dark')document.body.classList.add('dark');$('#theme').onclick=()=>{document.body.classList.toggle('dark');try{localStorage.setItem('rnk-theme',document.body.classList.contains('dark')?'dark':'light');}catch{}};
$('#today').textContent=dateLabel(koreaNow().date);
function render(){if(!displayData)return;$('#schedule').textContent=displayData.meals.map(m=>`${m.label} ${m.start}–${m.end}`).join('  /  ');const cards=$('#next-cards');cards.replaceChildren();const next=upcoming(displayData);if(!next.length){const empty=el('div',undefined,'empty');empty.append(el('h2','등록된 다음 식사가 없습니다'),el('p','새로운 식단이 등록되면 이곳에 표시됩니다.'));cards.append(empty);}next.forEach((m,i)=>{const card=el('article',undefined,'meal-card'+(!i?' featured':''));card.append(el('span',m.ongoing?'지금 식사 중':i?'그다음 식사':'다가오는 식사','label'),el('h2',m.label),el('div',`${dateLabel(m.date)} · ${m.start}–${m.end}`,'date'));const list=el('ul',undefined,'menu-list');m.menu.split(/\n|,\s*/).filter(s=>s.trim()).forEach(s=>list.append(el('li',s.trim())));card.append(list);cards.append(card);});renderWeekly();}
function headerRow(start){const row=el('tr');row.append(el('th','구분'));for(let i=0;i<7;i++){const date=addDays(start,i),th=el('th',dateLabel(date),date===koreaNow().date?'today':'');th.scope='col';row.append(th);}return row;}
function renderWeekly(){if(!displayData)return;$('#week-label').textContent=`${dateLabel(week)} – ${dateLabel(addDays(week,6))}`;const table=el('table');table.append(headerRow(week));displayData.meals.forEach(m=>{const row=el('tr'),head=el('th',m.label);head.scope='row';row.append(head);for(let i=0;i<7;i++){const day=displayData.days.find(d=>d.date===addDays(week,i));row.append(el('td',day?.[m.key]?.replace(/,\s*/g,'\n')||'미등록'));}table.append(row);});$('#weekly-table').replaceChildren(table);}
function renderEditor(start,source=published){editStart=start;$('#start-date').value=start;const table=el('table');table.append(headerRow(start));source.meals.forEach(m=>{const row=el('tr');row.append(el('th',m.label));for(let i=0;i<7;i++){const date=addDays(start,i),td=el('td'),input=el('textarea');input.dataset.date=date;input.dataset.key=m.key;input.setAttribute('aria-label',`${dateLabel(date)} ${m.label}`);input.maxLength=5000;input.value=source.days.find(d=>d.date===date)?.[m.key]||'';input.oninput=()=>dirty=true;td.append(input);row.append(td);}table.append(row);});$('#edit-table').replaceChildren(table);dirty=false;}
function collect(){if(!published)throw Error('식단을 먼저 불러와 주세요.');const days=Array.from({length:7},(_,i)=>({date:addDays(editStart,i),breakfast:'',lunch:'',dinner:''}));$$('#edit-table textarea').forEach(t=>days.find(d=>d.date===t.dataset.date)[t.dataset.key]=t.value.trim());return mergeDays(published,days);}
function safely(fn){return async()=>{try{await fn();}catch(e){status(e.message);}};}
$('#prev').onclick=()=>{week=addDays(week,-7);renderWeekly();};$('#next-week').onclick=()=>{week=addDays(week,7);renderWeekly();};$('#this-week').onclick=()=>{week=weekStart(koreaNow().date);renderWeekly();};$('#print').onclick=()=>window.print();
$('#fill-dates').onclick=safely(()=>{const date=$('#start-date').value;if(!validDate(date))throw Error('시작일을 선택하세요.');if(dirty&&!confirm('저장하지 않은 입력 내용을 바꾸고 선택한 주를 불러올까요?'))return;renderEditor(date);status('선택한 날짜부터 7일을 불러왔습니다.');});
$('#apply-paste').onclick=safely(()=>{const rows=parseTSV($('#paste').value);keys.forEach((k,r)=>$$(`#edit-table textarea[data-key="${k}"]`).forEach((t,c)=>t.value=rows[r][c]));dirty=true;status('붙여넣기를 적용했습니다. 입력 내용을 확인하세요.');});
$('#save').onclick=safely(()=>{localStorage.setItem('rnk-draft',JSON.stringify({start:editStart,data:collect()}));dirty=false;status('이 브라우저에 임시 저장했습니다. 아직 공개되지 않았습니다.');});
$('#restore').onclick=safely(()=>{const raw=localGet('rnk-draft');if(!raw)throw Error('임시 저장된 식단이 없습니다.');const draft=JSON.parse(raw);validate(draft.data);if(!validDate(draft.start))throw Error('임시 저장 날짜가 올바르지 않습니다.');if(dirty&&!confirm('현재 입력을 임시 저장된 내용으로 바꿀까요?'))return;renderEditor(draft.start,draft.data);dirty=true;status('임시 저장을 불러왔습니다.');});
$('#preview').onclick=safely(()=>{displayData=collect();week=editStart;render();$('#preview-banner').hidden=false;tab('weekly');location.hash='weekly';status('');});$('#exit-preview').onclick=()=>{displayData=published;$('#preview-banner').hidden=true;render();};
$('#download').onclick=safely(()=>{const data=collect(),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='menu.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('menu.json을 내려받았습니다. 백업하거나 GitHub에 반영할 수 있습니다.');});
$('#import').onchange=safely(async()=>{const file=$('#import').files[0];if(!file)return;if(file.size>2000000)throw Error('파일은 2MB 이하만 가져올 수 있습니다.');const data=validate(JSON.parse((await file.text()).replace(/^\uFEFF/,'')));if(dirty&&!confirm('현재 입력을 가져온 파일의 내용으로 바꿀까요?'))return;const start=data.days[0]?.date||editStart;renderEditor(start,data);dirty=true;status('파일의 첫 7일을 입력표로 가져왔습니다. 저장 전 확인하세요.');});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function request(payload){const response=await fetch(apiURL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),redirect:'follow',signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('서버 응답 오류입니다. 잠시 후 다시 시도하세요.');const result=await response.json();if(!result.ok)throw Error(result.error||'요청을 처리하지 못했습니다.');return result;}
$('#publish').onclick=safely(async()=>{if(!apiURL)throw Error('아직 저장 서버가 연결되지 않았습니다. README의 Apps Script 설정을 완료해 주세요.');const password=$('#password').value;if(!password)throw Error('관리자 비밀번호를 입력하세요.');const data=collect();if(!confirm('입력한 식단을 모든 방문자에게 공개할까요?'))return;$('#publish').disabled=true;status('서버에 저장하고 있습니다…');try{const result=await request({action:'save',password,expectedRevision:revision,data});revision=result.revision;published=validate(result.data);displayData=published;dirty=false;$('#preview-banner').hidden=true;$('#password').value='';render();status('공개 저장을 완료했습니다. 모든 기기에서 변경한 식단을 볼 수 있습니다.');}finally{$('#publish').disabled=false;}});
async function load(){try{const cfg=await fetch('./config.json',{cache:'no-store'});if(!cfg.ok)throw Error('설정 파일을 불러오지 못했습니다.');const config=await cfg.json();apiURL=config.apiUrl||'';if(apiURL&&!/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(apiURL))throw Error('Apps Script 배포 URL 설정을 확인하세요.');$('#connection').textContent=apiURL?'관리자 비밀번호를 입력한 뒤 공개 저장을 누르면 모든 방문자에게 반영됩니다.':'저장 서버 연결 대기 중입니다. Apps Script를 배포하고 config.json에 URL을 입력하세요. 식단 작성·임시 저장·미리보기는 지금 사용할 수 있습니다.';const response=await fetch(apiURL||'./data/menu.json',{cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('식단을 불러오지 못했습니다.');const result=await response.json();if(apiURL){if(!result.ok)throw Error(result.error||'서버 설정을 확인하세요.');revision=result.revision;published=validate(result.data);}else published=validate(result);displayData=published;render();renderEditor(editStart);}catch(e){$('#next-cards').replaceChildren(el('div','식단을 불러오지 못했습니다. '+e.message,'empty'));status('페이지를 새로고침해 다시 시도하세요.');$$('#admin button').forEach(b=>b.disabled=true);}}
load();setInterval(()=>{if(displayData)render();},60000);
