import {keys,moscowNow,addDays,weekStart,dateLabel,validate,upcoming,parseTSV,mergeDays,validDate} from './core.js';
import {validateVocDraft,validateReplyDraft,validateVocList,validatePhotoPayload,formatVocDate} from './voc.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let published,displayData,week=weekStart(moscowNow().date),editStart=week,dirty=false,apiURL='',revision=null,vocPosts=[],adminVocPosts=[],vocReady=false;
function status(text){$('#status').textContent=text;}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function localGet(key){try{return localStorage.getItem(key);}catch{return null;}}
function tab(id){const tabs=['next','weekly','menu-voc','lodging-voc','admin'];if(!tabs.includes(id))id='next';for(const s of tabs)$('#'+s).hidden=s!==id;$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===id);if(b.dataset.tab===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
$$('[data-tab]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.tab;tab(b.dataset.tab);});window.addEventListener('hashchange',()=>tab(location.hash.slice(1)));tab(location.hash.slice(1));
if(localGet('rnk-theme')==='dark')document.body.classList.add('dark');$('#theme').onclick=()=>{document.body.classList.toggle('dark');try{localStorage.setItem('rnk-theme',document.body.classList.contains('dark')?'dark':'light');}catch{}};
$('#today').textContent=dateLabel(moscowNow().date);
function render(){if(!displayData)return;$('#schedule').textContent=displayData.meals.map(m=>`${m.label} ${m.start}–${m.end}`).join('  /  ');const cards=$('#next-cards');cards.replaceChildren();const next=upcoming(displayData);if(!next.length){const empty=el('div',undefined,'empty');empty.append(el('h2','등록된 다음 식사가 없습니다'),el('p','새로운 식단이 등록되면 이곳에 표시됩니다.'));cards.append(empty);}next.forEach((m,i)=>{const card=el('article',undefined,'meal-card'+(!i?' featured':''));card.append(el('span',m.ongoing?'지금 식사 중':i?'그다음 식사':'다가오는 식사','label'),el('h2',m.label),el('div',`${dateLabel(m.date)} · ${m.start}–${m.end}`,'date'));const list=el('ul',undefined,'menu-list');m.menu.split(/\n|,\s*/).filter(s=>s.trim()).forEach(s=>list.append(el('li',s.trim())));card.append(list);cards.append(card);});renderWeekly();}
function headerRow(start){const row=el('tr');row.append(el('th','구분'));for(let i=0;i<7;i++){const date=addDays(start,i),th=el('th',dateLabel(date),date===moscowNow().date?'today':'');th.scope='col';row.append(th);}return row;}
function renderWeekly(){if(!displayData)return;$('#week-label').textContent=`${dateLabel(week)} – ${dateLabel(addDays(week,6))}`;const table=el('table');table.append(headerRow(week));displayData.meals.forEach(m=>{const row=el('tr'),head=el('th',m.label);head.scope='row';row.append(head);for(let i=0;i<7;i++){const day=displayData.days.find(d=>d.date===addDays(week,i));row.append(el('td',day?.[m.key]?.replace(/,\s*/g,'\n')||'미등록'));}table.append(row);});$('#weekly-table').replaceChildren(table);}
function renderEditor(start,source=published){editStart=start;$('#start-date').value=start;const table=el('table');table.append(headerRow(start));source.meals.forEach(m=>{const row=el('tr');row.append(el('th',m.label));for(let i=0;i<7;i++){const date=addDays(start,i),td=el('td'),input=el('textarea');input.dataset.date=date;input.dataset.key=m.key;input.setAttribute('aria-label',`${dateLabel(date)} ${m.label}`);input.maxLength=5000;input.value=source.days.find(d=>d.date===date)?.[m.key]||'';input.oninput=()=>dirty=true;td.append(input);row.append(td);}table.append(row);});$('#edit-table').replaceChildren(table);dirty=false;}
function collect(){if(!published)throw Error('식단을 먼저 불러와 주세요.');const days=Array.from({length:7},(_,i)=>({date:addDays(editStart,i),breakfast:'',lunch:'',dinner:''}));$$('#edit-table textarea').forEach(t=>days.find(d=>d.date===t.dataset.date)[t.dataset.key]=t.value.trim());return mergeDays(published,days);}
function safely(fn){return async(...args)=>{try{await fn(...args);}catch(e){status(e.message);}};}
$('#prev').onclick=()=>{week=addDays(week,-7);renderWeekly();};$('#next-week').onclick=()=>{week=addDays(week,7);renderWeekly();};$('#this-week').onclick=()=>{week=weekStart(moscowNow().date);renderWeekly();};$('#print').onclick=()=>window.print();
$('#fill-dates').onclick=safely(()=>{const date=$('#start-date').value;if(!validDate(date))throw Error('시작일을 선택하세요.');if(dirty&&!confirm('저장하지 않은 입력 내용을 바꾸고 선택한 주를 불러올까요?'))return;const monday=weekStart(date);renderEditor(monday);status('선택한 주의 월요일부터 7일을 불러왔습니다.');});
$('#apply-paste').onclick=safely(()=>{const rows=parseTSV($('#paste').value);keys.forEach((k,r)=>$$(`#edit-table textarea[data-key="${k}"]`).forEach((t,c)=>t.value=rows[r][c]));dirty=true;status('붙여넣기를 적용했습니다. 입력 내용을 확인하세요.');});
$('#save').onclick=safely(()=>{localStorage.setItem('rnk-draft',JSON.stringify({start:editStart,data:collect()}));dirty=false;status('이 브라우저에 임시 저장했습니다. 아직 공개되지 않았습니다.');});
$('#restore').onclick=safely(()=>{const raw=localGet('rnk-draft');if(!raw)throw Error('임시 저장된 식단이 없습니다.');const draft=JSON.parse(raw);validate(draft.data);if(!validDate(draft.start))throw Error('임시 저장 날짜가 올바르지 않습니다.');if(dirty&&!confirm('현재 입력을 임시 저장된 내용으로 바꿀까요?'))return;renderEditor(draft.start,draft.data);dirty=true;status('임시 저장을 불러왔습니다.');});
$('#preview').onclick=safely(()=>{displayData=collect();week=editStart;render();$('#preview-banner').hidden=false;tab('weekly');location.hash='weekly';status('');});$('#exit-preview').onclick=()=>{displayData=published;$('#preview-banner').hidden=true;render();};
$('#download').onclick=safely(()=>{const data=collect(),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='menu.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('menu.json을 내려받았습니다. 백업하거나 GitHub에 반영할 수 있습니다.');});
$('#import').onchange=safely(async()=>{const file=$('#import').files[0];if(!file)return;if(file.size>2000000)throw Error('파일은 2MB 이하만 가져올 수 있습니다.');const data=validate(JSON.parse((await file.text()).replace(/^\uFEFF/,'')));if(dirty&&!confirm('현재 입력을 가져온 파일의 내용으로 바꿀까요?'))return;const start=weekStart(data.days[0]?.date||editStart);renderEditor(start,data);dirty=true;status('파일의 첫 주를 월요일 기준 입력표로 가져왔습니다. 저장 전 확인하세요.');});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function request(payload){const response=await fetch(apiURL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),redirect:'follow',signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('서버 응답 오류입니다. 잠시 후 다시 시도하세요.');const result=await response.json();if(!result.ok)throw Error(result.error||'요청을 처리하지 못했습니다.');return result;}
function renderVoc(){for(const section of $$('.voc-section')){const category=section.dataset.category,list=section.querySelector('.voc-list'),posts=vocPosts.filter(p=>p.category===category);list.replaceChildren();if(!posts.length){const empty=el('div',undefined,'empty');empty.append(el('h2','아직 등록된 의견이 없습니다'),el('p','첫 번째 의견을 남겨주세요.'));list.append(empty);continue;}posts.forEach(post=>list.append(vocCard(post,false)));}}
function renderAdminVoc(){const list=$('#admin-voc-list');list.replaceChildren();if(!adminVocPosts.length){list.append(el('div','등록된 의견이 없습니다.','empty'));return;}adminVocPosts.forEach(post=>list.append(vocCard(post,true)));}
function addPhoto(card,photo){const image=el('img',undefined,'voc-photo');image.src=`data:${photo.mimeType};base64,${photo.data}`;image.alt='숙소 VoC 첨부 사진';image.loading='lazy';card.append(image);}
function makeReplyForm(post){const form=el('form',undefined,'reply-form'),heading=el('strong','답글 작성'),author=el('input'),content=el('textarea'),adminLabel=el('label',undefined,'reply-admin-toggle'),admin=el('input'),passwordLabel=el('label',undefined,'reply-password'),password=el('input'),button=el('button','답글 등록','secondary');author.name='author';author.maxLength=30;author.placeholder='이름 또는 닉네임 (익명 가능)';author.setAttribute('aria-label','답글 작성자');content.name='content';content.maxLength=1000;content.required=true;content.rows=3;content.placeholder='답글을 입력하세요.';admin.type='checkbox';admin.name='asAdmin';adminLabel.append(admin,document.createTextNode(' 관리자로 작성'));password.type='password';password.name='password';password.autocomplete='current-password';password.placeholder='관리자 비밀번호';passwordLabel.append(document.createTextNode('관리자 비밀번호 '),password);passwordLabel.hidden=true;admin.onchange=()=>{passwordLabel.hidden=!admin.checked;password.required=admin.checked;if(admin.checked)author.value='';author.disabled=admin.checked;if(!admin.checked)password.value='';};form.append(heading,author,content,adminLabel,passwordLabel,button);form.onsubmit=safely(async event=>{event.preventDefault();if(!vocReady)throw Error('Apps Script 코드를 최신 버전으로 업데이트하고 다시 배포해 주세요.');const reply=validateReplyDraft(Object.fromEntries(new FormData(form)));button.disabled=true;try{const result=await request({action:'createVocReply',id:post.id,...reply});vocPosts=validateVocList(result.posts);renderVoc();status(reply.asAdmin?'관리자 답글이 등록되었습니다.':'답글이 등록되었습니다.');}finally{button.disabled=false;}});return form;}
function vocCard(post,isAdmin){const card=el('article',undefined,'voc-card'),meta=el('div',undefined,'voc-meta'),category=post.category==='menu'?'메뉴':'숙소';meta.append(el('span',`${category} · ${post.author} · ${formatVocDate(post.createdAt)}`),el('span',post.status,'status-badge'));card.append(meta,el('h3',post.title),el('p',post.content,'voc-content'));if(post.photo)addPhoto(card,post.photo);else if(post.hasPhoto){const photoButton=el('button','사진 보기','secondary photo-button');photoButton.onclick=safely(async()=>{photoButton.disabled=true;try{const response=await fetch(`${apiURL}?resource=vocPhoto&id=${encodeURIComponent(post.id)}`,{cache:'no-store',signal:AbortSignal.timeout(30000)}),result=await response.json();if(!result.ok)throw Error(result.error||'사진을 불러오지 못했습니다.');addPhoto(card,validatePhotoPayload(result.photo));photoButton.remove();}finally{photoButton.disabled=false;}});card.append(photoButton);}if(post.replies.length){const replies=el('div',undefined,'voc-replies');post.replies.forEach(item=>{const reply=el('div',undefined,'voc-reply'),head=el('div',undefined,'reply-head');head.append(el('strong',item.author));if(item.isAdmin)head.append(el('span','관리자','admin-badge'));head.append(el('time',formatVocDate(item.createdAt)));reply.append(head,el('p',item.content));replies.append(reply);});card.append(replies);}if(isAdmin){const actions=el('div',undefined,'admin-voc-actions'),deleteButton=el('button','게시글 삭제','secondary danger');deleteButton.onclick=safely(async()=>{const password=$('#password').value;if(!password)throw Error('관리자 비밀번호를 입력하세요.');if(!confirm('이 VoC 게시글과 답글을 모두 삭제할까요?'))return;deleteButton.disabled=true;try{const result=await request({action:'deleteVoc',password,id:post.id});adminVocPosts=validateVocList(result.posts);renderAdminVoc();await loadVoc();status('VoC 게시글을 삭제했습니다.');}finally{deleteButton.disabled=false;}});actions.append(deleteButton);card.append(actions);}else card.append(makeReplyForm(post));return card;}
function setVocReady(ready){vocReady=ready;$$('.voc-form button[type="submit"]').forEach(button=>button.disabled=!ready);}
async function loadVoc(){setVocReady(false);if(!apiURL){$$('.voc-list').forEach(list=>list.replaceChildren(el('div','저장 서버를 연결하면 VoC 게시판을 사용할 수 있습니다.','empty')));return;}try{const response=await fetch(`${apiURL}?resource=voc`,{cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('VoC 서버 응답 오류입니다.');const result=await response.json();if(!result.ok||!Array.isArray(result.posts))throw Error('Apps Script 코드를 최신 버전으로 업데이트해 주세요.');vocPosts=validateVocList(result.posts);renderVoc();const ready=result.capabilities?.publicReplies===true&&result.capabilities?.lodgingPhoto===true;setVocReady(ready);if(!ready)status('공개 답글 기능을 사용하려면 Apps Script 코드를 최신 버전으로 업데이트하고 다시 배포해 주세요.');}catch(e){$$('.voc-list').forEach(list=>list.replaceChildren(el('div',e.message,'empty')));}}
async function preparePhoto(file){if(!file||!file.size)return null;if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('JPG, PNG, WebP 사진만 첨부할 수 있습니다.');if(file.size>10*1024*1024)throw Error('원본 사진은 10MB 이하여야 합니다.');const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(!blob||blob.size>950000)throw Error('사진을 압축할 수 없습니다. 더 작은 사진을 선택해 주세요.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('사진을 읽지 못했습니다.'));reader.readAsDataURL(blob);});return validatePhotoPayload({mimeType:'image/jpeg',data});}
for(const section of $$('.voc-section')){const form=section.querySelector('.voc-form'),category=section.dataset.category;form.onsubmit=safely(async event=>{event.preventDefault();if(!apiURL)throw Error('저장 서버를 먼저 연결해 주세요.');if(!vocReady)throw Error('Apps Script 코드를 최신 버전으로 업데이트하고 다시 배포해 주세요.');const values=Object.fromEntries(new FormData(form));if(values.website)return;const draft=validateVocDraft({...values,category}),button=form.querySelector('button[type="submit"]'),photo=category==='lodging'?await preparePhoto(form.elements.photo.files[0]):null;button.disabled=true;status('의견을 등록하고 있습니다…');try{const result=await request({action:'createVoc',...draft,photo,website:values.website||''});vocPosts=validateVocList(result.posts);form.reset();renderVoc();status('공개 의견이 등록되었습니다.');}finally{button.disabled=!vocReady;}});section.querySelector('.voc-refresh').onclick=safely(async()=>{await loadVoc();if(vocReady)status('최신 의견을 불러왔습니다.');});}
$('#admin-voc-refresh').onclick=safely(async()=>{const password=$('#password').value;if(!password)throw Error('관리자 비밀번호를 입력하세요.');const result=await request({action:'listVocAdmin',password});adminVocPosts=validateVocList(result.posts);renderAdminVoc();status('삭제할 VoC 게시글을 불러왔습니다.');});
$('#publish').onclick=safely(async()=>{if(!apiURL)throw Error('아직 저장 서버가 연결되지 않았습니다. README의 Apps Script 설정을 완료해 주세요.');const password=$('#password').value;if(!password)throw Error('관리자 비밀번호를 입력하세요.');const data=collect();if(!confirm('입력한 식단을 모든 방문자에게 공개할까요?'))return;$('#publish').disabled=true;status('서버에 저장하고 있습니다…');try{const result=await request({action:'save',password,expectedRevision:revision,data});revision=result.revision;published=validate(result.data);displayData=published;dirty=false;$('#preview-banner').hidden=true;$('#password').value='';render();status('공개 저장을 완료했습니다. 모든 기기에서 변경한 식단을 볼 수 있습니다.');}finally{$('#publish').disabled=false;}});
async function load(){try{const cfg=await fetch('./config.json',{cache:'no-store'});if(!cfg.ok)throw Error('설정 파일을 불러오지 못했습니다.');const config=await cfg.json();apiURL=config.apiUrl||'';if(apiURL&&!/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(apiURL))throw Error('Apps Script 배포 URL 설정을 확인하세요.');let serverError='';if(apiURL){try{const response=await fetch(apiURL,{cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('식단 서버 응답 오류입니다.');const result=await response.json();if(!result.ok)throw Error(result.error||'서버 설정을 확인하세요.');revision=result.revision;published=validate(result.data);}catch(e){serverError=e.message;}}if(!published){const fallback=await fetch('./data/menu.json',{cache:'no-store'});if(!fallback.ok)throw Error('기본 식단을 불러오지 못했습니다.');published=validate(await fallback.json());}$('#connection').textContent=apiURL&&!serverError?'관리자 비밀번호로 메뉴를 저장하거나 VoC 게시글을 삭제할 수 있습니다. 관리자 답글은 각 게시판에서 작성하세요.':apiURL?`저장 서버 연결이 아직 준비되지 않았습니다: ${serverError} Apps Script에서 setup 함수를 실행해 주세요.`:'저장 서버 연결 대기 중입니다. Apps Script를 배포하고 config.json에 URL을 입력하세요.';displayData=published;render();renderEditor(editStart);await loadVoc();}catch(e){$('#next-cards').replaceChildren(el('div','식단을 불러오지 못했습니다. '+e.message,'empty'));status('페이지를 새로고침해 다시 시도하세요.');$$('#admin button').forEach(b=>b.disabled=true);}}
load();setInterval(()=>{if(displayData)render();},60000);
