export const keys=['breakfast','lunch','dinner'];
export const mealSchedule=[{key:'breakfast',label:'조식',start:'07:30',end:'08:30'},{key:'lunch',label:'중식',start:'12:30',end:'13:30'},{key:'dinner',label:'석식',start:'18:30',end:'19:30'}];
export function moscowNow(now=new Date()){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now).map(p=>[p.type,p.value]));return {date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`};}
export function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;}
export function addDays(s,n){const d=new Date(s+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
export function weekStart(s){const day=new Date(s+'T00:00:00Z').getUTCDay();return addDays(s,-((day+6)%7));}
export function dateLabel(s){return new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short',timeZone:'UTC'}).format(new Date(s+'T00:00:00Z'));}
export function validate(data){if(!data||data.version!==1||!Array.isArray(data.days)||data.days.length>3660||!Array.isArray(data.meals)||data.meals.length!==3)throw Error('지원하지 않는 식단 형식입니다.');let previous='00:00';data.meals.forEach((m,i)=>{if(m.key!==keys[i]||typeof m.label!=='string'||m.label.length>30||!/^([01]\d|2[0-3]):[0-5]\d$/.test(m.start)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(m.end)||m.start>=m.end||m.start<previous)throw Error('식사 시간 설정이 올바르지 않습니다.');previous=m.end;});const seen=new Set();for(const d of data.days){if(!validDate(d.date)||seen.has(d.date)||keys.some(k=>typeof d[k]!=='string'||d[k].length>5000))throw Error('식단 날짜 또는 메뉴가 올바르지 않습니다.');seen.add(d.date);}return {...data,meals:mealSchedule.map(m=>({...m}))};}
export function upcoming(data,now=new Date()){const k=moscowNow(now);return [...data.days].sort((a,b)=>a.date.localeCompare(b.date)).flatMap(d=>data.meals.map(m=>({...m,date:d.date,menu:d[m.key],ongoing:d.date===k.date&&m.start<=k.time&&k.time<m.end}))).filter(m=>m.menu.trim()&&(m.date>k.date||(m.date===k.date&&m.end>k.time))).slice(0,2);}
export function parseTSV(raw){const rows=[];let row=[],cell='',quoted=false;raw=raw.replace(/\r\n/g,'\n').replace(/\r/g,'\n');for(let i=0;i<raw.length;i++){const c=raw[i];if(c==='"'&&(quoted||cell==='')){if(quoted&&raw[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c==='\t'||c==='\n')){row.push(cell);cell='';if(c==='\n'){rows.push(row);row=[];}}else cell+=c;}if(quoted)throw Error('닫히지 않은 따옴표가 있습니다. 엑셀 범위를 다시 복사하세요.');row.push(cell);rows.push(row);while(rows.length&&rows.at(-1).every(c=>!c))rows.pop();if(rows.length!==3||rows.some(r=>r.length!==7))throw Error('조식·중식·석식 3행 × 7열을 붙여넣어 주세요.');return rows;}
export function mergeDays(data,days){const map=new Map(data.days.map(d=>[d.date,d]));days.forEach(d=>map.set(d.date,d));return validate({...data,updatedAt:new Date().toISOString(),days:[...map.values()].sort((a,b)=>a.date.localeCompare(b.date))});}
